# Generated by Django 6.0.3 on 2026-03-18 13:43

import apps.user.models
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "uuid",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=11, null=True, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(2, "已锁定"), (1, "已激活"), (0, "未激活")], default=0
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "officeAuth_officeuser",
            },
            managers=[
                ("objects", apps.user.models.UserManager()),
            ],
        ),
    ]
