# Generated by Django 6.0.3 on 2026-03-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officeuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="officeuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="officeuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="officeuser",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="officeuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="officeuser",
            name="status",
            field=models.IntegerField(
                choices=[(2, "已锁定"), (1, "已激活"), (0, "未激活")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="officeuser",
            name="telephone",
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
